version: '3.7'

networks:
  todolist:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Zqq103435@
      - MYSQL_DATABASE=micro_todolist
      - MYSQL_USER=micro_todolist
      - MYSQL_PASSWORD=micro_todolist
      - TZ=Europe/Berlin
    ports:
      - "3306:3306"
    networks:
      - todolist